src/Entity/Presentation.php
<?php

namespace App\Entity;

use App\Repository\PresentationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PresentationRepository::class)]
class Presentation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $intituleDescription = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $intituleExpertise = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $expertise = null;

    #[ORM\Column(length: 255)]
    private ?string $intituleAutre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $autre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntituleDescription(): ?string
    {
        return $this->intituleDescription;
    }

    public function setIntituleDescription(string $intituleDescription): static
    {
        $this->intituleDescription = $intituleDescription;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getIntituleExpertise(): ?string
    {
        return $this->intituleExpertise;
    }

    public function setIntituleExpertise(string $intituleExpertise): static
    {
        $this->intituleExpertise = $intituleExpertise;

        return $this;
    }

    public function getExpertise(): ?string
    {
        return $this->expertise;
    }

    public function setExpertise(string $expertise): static
    {
        $this->expertise = $expertise;

        return $this;
    }

    public function getIntituleAutre(): ?string
    {
        return $this->intituleAutre;
    }

    public function setIntituleAutre(string $intituleAutre): static
    {
        $this->intituleAutre = $intituleAutre;

        return $this;
    }

    public function getAutre(): ?string
    {
        return $this->autre;
    }

    public function setAutre(string $autre): static
    {
        $this->autre = $autre;

        return $this;
    }
}

src/Controller/PresentationController.php
<?php

namespace App\Controller;

use App\Repository\PresentationRepository; // Import the PresentationRepository class
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PresentationController extends AbstractController
{
    #[Route('/presentation', name: 'app_presentation')]
    public function index(PresentationRepository $manage): Response
    {
        $Presentation = $manage->findAll(); // Call the findAll() method from the PresentationRepository class
        return $this->render('presentation/index.html.twig', [
            'presentation' => $Presentation
        ]);
    }
}
  

  

templates/presentation/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} Presentations{% endblock %}
{% block stylesheets %}<link rel="stylesheet" href="assets/css/presentation.css"> {% endblock %}
{% block body %}
    <main class="container presentation">
        {% for value in presentation %}
            {% if app.user %}
            {% if  is_granted('ROLE_ADMIN') %} {# si l'utilisateur est connecté et qu'il est admin #}

           l     <div class="btns-edit">
                    <button class="btn-edit" onclick="window.location.href='/admin'">Modifier</button>
                </div>  
            {% endif %}
            {% endif %}
            <div class="header">
                <h1>Présentation d'Alex, Photographe Passionné</h1>
            </div>
            <div class="about">
                <h2>{{value.intituleDescription}}</h2>
                <p>{{value.description}}</p>
            </div>
            <div class="expertise">
                <h2>{{value.intituleExpertise}}</h2>
                <p>{{value.expertise}}</p>
            </div>
            <div class="others">
                <h2>{{value.intituleAutre}}</h2>
                <p>{{value.autre}}</p>
            </div>
        {% endfor %}
    </main>
{% endblock %}